version: '3'

services:

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mongo_main:
    image: mongo:latest
    container_name: mongo-main
    ports:
      - "27017:27017"
    volumes:
      - mongo_main_data:/data/db

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    container_name: main-db
    environment:
      POSTGRES_DB: "main"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"

    ports:
      - "5433:5432"

  db-1:
    image: postgres
    restart: always
    shm_size: 128mb
    container_name: server1-db
    environment:
      POSTGRES_DB: "server1"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"

    ports:
      - "5434:5432"


volumes:
    rabbitmq_data:
    mongo_main_data:
